[package]
authors = ["Brendan C. Ward"]
name = "rastertiler"
description = "Render a single-band GeoTIFF to MBTiles"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
# gdal = "0.12.0"
gdal = {path = "../georust_gdal"}
gdal-sys = "0.6.0"
hex = "0.4"
png = "0.17.5"
itertools = "0.10.3"
libc = "0.2"
r2d2 = "0.8.9"
r2d2_sqlite = "0.20.0"
rusqlite = "0.27.0"

[dev-dependencies]
rstest = "0.12.0"

[profile.dev.package.png]
opt-level = 3
[profile.dev.package.deflate]
opt-level = 3
