[package]
authors = ["Brendan C. Ward"]
name = "rastertiler"
description = "Render a single-band GeoTIFF to MBTiles"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
crossbeam = "0.8"
# gdal = "0.12"
# gdal-sys = "0.6"
# gdal = {path = "../georust_gdal"}
gdal = { git = "https://github.com/georust/gdal", rev = "d640dd734e30de997ace613b650181b7c3187b53" }
gdal-sys = { git = "https://github.com/georust/gdal", rev = "d640dd734e30de997ace613b650181b7c3187b53" }
hex = "0.4"
png = "0.17"
indicatif = "0.16"
itertools = "0.10"
libc = "0.2"
r2d2 = "0.8.9"
r2d2_sqlite = "0.20"
rusqlite = "0.27"
rust-crypto = "0.2"
seahash = "4.1"

[dev-dependencies]
rstest = "0.12"

[profile.dev.package.png]
opt-level = 3
[profile.dev.package.deflate]
opt-level = 3

[profile.dev]
panic = "abort"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true
