name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} ${{ matrix.platform }} (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "macos-11", "macos-10.15"]
        platform: ["x86_64"]
        toolchain: ["stable", "nightly"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: clippy

      - name: Rust version
        run: |
          cargo --version --verbose

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy --package rastertiler -- -D warnings

      - name: Run tests
        run: |
          cargo check
          cargo test --verbose
